[frontends]
  [frontends.frontend1]
  priority = 1
  backend = "backend1"

  [frontends.frontend1.routes.test_1]
  rule = "Host:localhost"

[backends]
  [backends.backend1]
  [backends.backend1.servers.server1]
  url = "http://httpd:80"
  weight = 1
